version: '3.8'

services:
  # PostgreSQL 서비스
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: project_alpha
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # 개발 서버 (Prisma Studio 포함)
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
      - "24678:24678"  # Vite HMR
      - "5555:5555"    # Prisma Studio
    volumes:
      - .:/app
      - /app/node_modules
      - /app/build
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/project_alpha?schema=public
      - VITE_DEV_SERVER_HOST=0.0.0.0
      - VITE_DEV_SERVER_PORT=24678
    depends_on:
      postgres:
        condition: service_healthy
    command: sh -c "npx prisma migrate deploy && pnpm run dev"

volumes:
  postgres_data:
