apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-alpha
  labels:
    app: project-alpha
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-alpha
  template:
    metadata:
      labels:
        app: project-alpha
    spec:
      containers:
      - name: project-alpha
        image: project-alpha:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"
        - name: DATABASE_URL
          value: "postgresql://postgres:postgres@postgres-service:5432/project_alpha"
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: project-alpha-service
spec:
  selector:
    app: project-alpha
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
