apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-alpha
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-alpha
  template:
    metadata:
      labels:
        app: project-alpha
    spec:
      # Add image pull secret for GHCR
      imagePullSecrets:
        - name: ghcr-credentials
  template:
    metadata:
      labels:
        app: project-alpha
    spec:
      containers:
      - name: project-alpha
        image: ghcr.io/formalbridge/project_alpha:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: db-url-secret
              key: URL
        envFrom:
        - secretRef:
            name: env-secret
        resources:
          requests:
            cpu: "50m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
      imagePullSecrets:
      - name: ghcr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: project-alpha-service
spec:
  selector:
    app: project-alpha
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: ClusterIP
