apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-alpha
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-alpha
  template:
    metadata:
      labels:
        app: project-alpha
    spec:
      containers:
      - name: project-alpha
        image: your-dockerhub-id/project-alpha:latest # 1. 이미지 주소 수정
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"
        - name: DATABASE_URL # 2. Secret을 사용하도록 수정
          valueFrom:
            secretKeyRef:
              name: db-url-secret
              key: URL
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: project-alpha-service
spec:
  selector:
    app: project-alpha
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: LoadBalancer
