apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: project-alpha-ingress
  annotations:
    # 이 annotation은 Nginx Ingress Controller에게 경로를 재작성하도록 지시합니다.
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
  - host: music.formabridge.cc
    http:
      paths:
      - path: /()(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: project-alpha-service
            port:
              number: 80
