apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: project-alpha-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"  # MinIO 업로드 허용
spec:
  ingressClassName: nginx
  rules:
  - host: music.formabridge.cc
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: project-alpha-service
            port:
              number: 80
  - host: file.formabridge.cc
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: minio-service
            port:
              number: 9000
  - host: file-console.formabridge.cc
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: minio-service
            port:
              number: 9001
