apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_DB: cHJvamVjdF9hbHBoYQ==  # project_alpha
  POSTGRES_USER: cG9zdGdyZXM=         # postgres
  POSTGRES_PASSWORD: cG9zdGdyZXM=     # postgres (base64 encoded)
