name: Build check

on:
  pull_request:

run-name: 'Build Check'

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v4

      - uses: pnpm/action-setup@v3

      - name: Install dependencies
        run: |
          pnpm install

      - name: Build
        run: |
          pnpm build
