name: Code check

on:
  pull_request:

run-name: 'Code Check'

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v4

      - uses: pnpm/action-setup@v3

      - name: Install dependencies
        run: |
          pnpm install

      - name: Lint
        run: |
          pnpm run lint

  Format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v4

      - uses: pnpm/action-setup@v3

      - name: Install dependencies
        run: |
          pnpm install

      - name: Format
        run: |
          pnpm run format
